/********************************************************************
 * Autogenerated file, do not edit.
 *******************************************************************/

#ifndef __GATT_DB_H
#define __GATT_DB_H

#include "bg_gattdb_def.h"

extern const struct bg_gattdb_def bg_gattdb_data;

#define gattdb_service_changed_char           3
#define gattdb_database_hash                  6
#define gattdb_client_support_features        8
#define gattdb_device_name                    11
#define gattdb_board_serial                   22
#define gattdb_board_rev                      24
#define gattdb_firmware_rev                   26
#define gattdb_system_id                      28
#define gattdb_aio_digital_out                31
#define gattdb_batt_measurement               34
#define gattdb_power_source_type              38
#define gattdb_hall_state                     41
#define gattdb_hall_field_strength            44
#define gattdb_hall_control_point             47
#define gattdb_imu_acceleration               50
#define gattdb_imu_orientation                53
#define gattdb_imu_control_point              56
#define gattdb_es_uvindex                     60
#define gattdb_es_ambient_light               62
#define gattdb_es_temperature                 64
#define gattdb_es_humidity                    66
#define gattdb_ota_control                    69


#endif // __GATT_DB_H
